require("ibl").setup({
	enabled = true,
	debounce = 200,
	indent = {
		char = "│",
		tab_char = "│",
		smart_indent_cap = true,
		priority = 2,
	},
	whitespace = { remove_blankline_trail = true },
	scope = {
		enabled = true,
		char = "┃",
		show_start = false,
		show_end = false,
		injected_languages = true,
		priority = 1000,
	},
	exclude = {
		buftypes = {
			"nofile",
			"prompt",
			"quickfix",
			"terminal",
		},
		filetypes = {
			"",
			"alpha",
			"checkhealth",
			"dap-repl",
			"diff",
			"help",
			"lazy",
			"lspinfo",
			"mason",
			"notify",
			"NvimTree",
			"qf",
			"TelescopePrompt",
			"terminal",
			"toggleterm",
			"Trouble",
		},
	},
})
