require("tiny-inline-diagnostic").setup({
	preset = "simple",
	options = {
		show_source = { enabled = true, if_many = true },
		add_messages = true,
		set_arrow_to_diag_color = false,
		use_icons_from_diagnostic = true,
		show_all_diags_on_cursorline = false,
		break_line = { enabled = true, after = 80 },
		severity = {
			vim.diagnostic.severity.ERROR,
			vim.diagnostic.severity.WARN,
			vim.diagnostic.severity.INFO,
			vim.diagnostic.severity.HINT,
		},
	},
	disabled_ft = {
		"alpha",
		"checkhealth",
		"dap-repl",
		"diff",
		"help",
		"log",
		"notify",
		"NvimTree",
		"Outline",
		"qf",
		"TelescopePrompt",
		"toggleterm",
		"undotree",
		"vimwiki",
	},
})
