require("nvim-tree").setup({
	auto_reload_on_write = true,
	disable_netrw = true,
	hijack_cursor = true,
	hijack_netrw = true,
	hijack_unnamed_buffer_when_opening = true,
	respect_buf_cwd = true,
	sync_root_with_cwd = true,
	renderer = {
		full_name = false,
		group_empty = true,
		add_trailing = false,
		symlink_destination = true,
		highlight_git = "all",
		root_folder_label = ":.:s?.*?/..?",
		special_files = { "Cargo.toml", "Makefile", "README.md", "readme.md", "CMakeLists.txt" },
		indent_markers = {
			enable = true,
			inline_arrows = true,
		},
		icons = {
			show = {
				file = true,
				folder = true,
				folder_arrow = true,
				git = true,
			},
			padding = " ",
			symlink_arrow = " 󰁔 ",
			git_placement = "after",
		},
	},
	actions = {
		use_system_clipboard = true,
		change_dir = { enable = true, global = false },
		open_file = {
			quit_on_open = false,
			resize_window = true,
			window_picker = {
				enable = true,
				chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
				exclude = {
					buftype = { "help", "nofile", "prompt", "quickfix", "terminal" },
					filetype = { "dap-repl", "diff", "fugitive", "fugitiveblame", "git", "notify", "qf", "TelescopePrompt", "toggleterm", "undotree" },
				},
			},
		},
		remove_file = { close_window = true },
	},
	diagnostics = {
		enable = true,
		show_on_dirs = false,
		debounce_delay = 50,
	},
	filters = {
		enable = true,
		dotfiles = false,
		no_buffer = false,
		git_clean = false,
		git_ignored = true,
		no_bookmark = false,
		custom = { ".DS_Store" },
	},
	update_focused_file = {
		enable = true,
		update_root = { enable = true },
	},
	trash = { cmd = "gio trash" },
	git = { enable = true },
})
